# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.CharField(default='root', max_length=64),
            preserve_default=False,
        ),
    ]
