# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190125_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='time',
        ),
        migrations.AddField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 25, 17, 22, 25, 427000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
